### ISSUE TITLE
Minor change in rvest library

### ISSUE THREAD

**Issue by sajalshres** [gvsu-sta518/activity10-iteration#1]
@dykesb 

https://github.com/gvsu-sta518/activity10-iteration/blob/6c44dbae62a5603fe9d38fcd5b56230d4414f199/activity1001-scraping-iteration.Rmd#L38

https://github.com/tidyverse/rvest/blob/064ea35d8866532809f42dcfd712bd6cdbf262d2/NEWS.md?plain=1#L58

It seems like `html_node` is replaced with `html_element` and `html_nodes` is replaced with `html_elements` on [1.0.0](https://github.com/tidyverse/rvest/blob/064ea35d8866532809f42dcfd712bd6cdbf262d2/NEWS.md) release

**Comment by dykesb** [comment]
I updated this line directly in recent commit (2ef236a8e6746f37a70f60f77f51c7468927b851). There are more changes I need to make in this activity, unrelated to `html_nodes` vs. `html_elements`, but will make sure to be consistent with these updated functions.
